### ISSUE TITLE
[SOLVED] Compile error using "cargo install xplr"

### ISSUE THREAD

**Issue by vdoma** [sayanarijit/xplr#12]
I received the following error when using "cargo install xplr" on ubuntu. Any suggestions?

```sh
error: no rules expected the token `,`
   --> /home/vdoma/.cargo/registry/src/github.com-1ecc6299db9ec823/xplr-0.3.1/src/input.rs:373:29
    |
373 |                 | Self::Num9,
    |                             ^ no rules expected this token in macro call

error: aborting due to previous error

error: could not compile `xplr`.
```

**Comment by sayanarijit** [comment]
Weird... Can you please provide the output of `rustc --version`? Also, the Ubuntu version?

**Comment by idmyn** [comment]
I got this error too: `rustc 1.45.0 (5c1f21c3b 2020-07-13)` macOS Catalina (10.15.7)

**Comment by sayanarijit** [comment]
Probably because of https://github.com/rust-lang/rust/pull/74880/
So which was fixed in [rustc 1.48.0](https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1480-2020-11-19)

Can you try the latest version of Rustc? or you can also [download the standalone binary tarball](https://github.com/sayanarijit/xplr/releases/tag/v0.3.1).

**Comment by idmyn** [comment]
Yeah it installed happily after I updated my rust version :)

**Comment by sayanarijit** [comment]
Nice. I'll rename and keep this issue open for others having the same issue.

**Comment by vdoma** [comment]
I was using rustc version 1.47.0 on Ubuntu 20.10. Upgraded to rustc 1.51.0 and the problem went away. Thanks!

**Comment by sayanarijit** [comment]
FIxed: https://github.com/sayanarijit/xplr/pull/42
