### ISSUE TITLE
Improve the key bindings further (add `reckless` mode)

### ISSUE THREAD

**Issue by sayanarijit** [sayanarijit/xplr#142]
I like the key binding changes introduced in https://github.com/sayanarijit/xplr/commit/e0f82079008c1f7e0869465a8a8a0dee31edde10 so much that I'm now considering an even stricter behavior, where an invalid key press will take you to a mode where the only keys you can use will be `esc` to escape the mode and `ctrl-c` to quit the app. This will save you from yourself when you're going too fast, recklessly.

Comments? @maximbaz

**Comment by maximbaz** [comment]
Hmmmm certainly an interesting idea, but I'm not sure if it will be more useful or annoying 🤔 
But the more I think about it, the more I like.

Are you thinking even in default mode? So if I hit `n` instead of `j` to go down, then I need to `esc` before I can hit `j`?

It most certainly happened to me, not only in `xplr`, that for example I wanna search for `asdf`, I *think* I press `/` but I miss it, and then I type out the entire search term, wreaking havoc, only to realize that I didn't enter the search mode. With the strict mode, I can still be unlucky that my search term will match some existing keys, but if at least one of them is invalid, I'd be saved by the fail mode.

**Comment by sayanarijit** [comment]
I'll create a similar proof of concept PR to test it out.

**Comment by sayanarijit** [comment]
I think itll work best with a disable option.

**Comment by sayanarijit** [comment]
> Are you thinking even in default mode? So if I hit n instead of j to go down, then I need to esc before I can hit j?

Yes
