### ISSUE TITLE
Functionality

### ISSUE THREAD

**Issue by RustemB** [sayanarijit/xplr#187]
Can `*.style` fields be a function
to style it depend on file things
like
```lua
xplr.config.general.table.row.cols = {
    {
        format = "builtin.fmt_general_table_row_cols_1",
        style = { add_modifiers = nil, bg = nil, fg = function(m)
            if m.is_executable then
                return "#00ff00"
            end
        end, sub_modifiers = nil }
    },
}

```
or something like that

**Comment by sayanarijit** [comment]
Ideally I'd define colors in `xplr.config.node_types.executable` (doesn't exist yet), and let Rust handle most of the load. This way it'll be fast, we'll get better errors and things will stay simple.

But the issue with that approach is that it will color the whole line instead of a particular column, which I think is acceptable in this particular case.

**Comment by sayanarijit** [comment]
With https://github.com/sayanarijit/xplr/pull/188 it will be possible to set colors using escape sequence.

**Comment by sayanarijit** [comment]
Published https://github.com/sayanarijit/xplr/releases/tag/v0.11.0

**Comment by RustemB** [comment]
![image](https://user-images.githubusercontent.com/25725953/119336119-a85a1100-bca6-11eb-90b1-ffbaf9159137.png)
first bit doesn't colors

**Comment by sayanarijit** [comment]
Yes. I have already raised https://github.com/uttarayan21/ansi-to-tui/issues/3 for this.

**Comment by sayanarijit** [comment]
Until the issue is fixed, let's go with this workaround https://github.com/sayanarijit/xplr/pull/196
