### ISSUE TITLE
read-only mode

### ISSUE THREAD

**Issue by v217** [sayanarijit/xplr#22]
Hi,
Sorry couldn't find any docs on this.
Is there a way to disable write access to the filesystem.
I am looking for a file explorer to quickly span shells in different directories.

**Comment by sayanarijit** [comment]
You can actually remove all the keys that write to the filesystem from the config file.

**Comment by sayanarijit** [comment]
You might want to go through this doc https://github.com/sayanarijit/xplr/wiki/Key-Bindings

**Comment by v217** [comment]
OK, Thanks, but wouldn't an option "--read-only" be very useful.
Sometimes  you want to manipulate files, and sometimes you want to browse fastly through a filesystem, without actually remembering all the shortcuts of xplr, resting assured that there is no danger of accidentally moving or deleting anything?

**Comment by sayanarijit** [comment]
Got it. That's a valid use case. I'll keep it in mind while [implementing the CLI args](https://github.com/sayanarijit/xplr/wiki/TODO).

**Comment by sayanarijit** [comment]
With https://github.com/sayanarijit/xplr/pull/86 I have enabled read-only mode via config file. Now let's wait for the CLI args.

**Comment by v217** [comment]
That's awesome! `xplr` is the only filemanager I know with has this option. Thank you!

**Comment by sayanarijit** [comment]
FYI due to design restrictions, It will not be possible to for e.g. omit the "create file" option from the help menu. But the actual action to create the file will be omitted from the help menu.
Also, shell commands that perform read-only actions are also restricted in the read-only mode since there is no way to detect what they execute. e.g. the `?` key action that executes `less <help menu>` will not be visible in the read-only mode.

**Comment by v217** [comment]
Good to know! Thanks!
