### ISSUE TITLE
macos config dir issue

### ISSUE THREAD

**Issue by sayanarijit** [sayanarijit/xplr#230]
Is there a way to specify a configuration file directly? Or is there a way to make sure that mine is actually being sourced. I've installed 2 versions, 0.13.6 and 0.13.7 on macOS and it doesn't seem to be sourcing the configuration file located at `~/.config/xplr/init.lua`. I have used a very minimal config where I only modified one keybinding to using a more complex one  that I found online, as well as adding executable permissions to the `init.lua` file. Either way it isn't changed within the TUI of `xplr`.

_Originally posted by @lmburns in https://github.com/sayanarijit/xplr/discussions/2#discussioncomment-829133_

**Comment by sayanarijit** [comment]
Some investigation: https://github.com/sayanarijit/xplr/discussions/2#discussioncomment-829231

**Comment by lmburns** [comment]
I found the correct location for maOS. It is:
```
/Users/lucasburns/Library/Application Support/xplr
```
I found it from this simple rust program:
```rust
use std::path::PathBuf;

fn main() {

    let config_dir = dirs::config_dir()
        .unwrap_or_else(|| PathBuf::from("."))
        .join("xplr");

    println!("{}", config_dir.display());
}
```
A couple options could be to add an environment variable to set the configuration file, or perhaps to use [this](https://docs.rs/xdg/2.0.0/xdg/struct.BaseDirectories.html) crate instead of `dirs` or to use `xdg` alongside it.

This could be used to get the configuration directory. Like I said in the post this morning, I don't know any rust, but I could try and modify the original code.
```rust
fn main() {

    let xdg_dirs = xdg::BaseDirectories::with_prefix("xplr").unwrap();
    let config_file = xdg_dirs.find_config_file("init.lua");
    // let config_file = xdg_dirs.get_config_home(); // or this one, which just returns the directory
    println!("{:?}", config_file);
}
```

**Comment by sayanarijit** [comment]
Hey awesome research. I'd stay with dirs for now. the dirs::home_dir seems to point to the right home directory location. We just need to append `.config/xplr`.

**Comment by sayanarijit** [comment]
Self note: add -c cli option to specify config file.
