### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by sayanarijit** [sayanarijit/xplr#263]
xplr is getting stable. Let's start the exticing stuff... Extensive Documention.

Thanks to [Brodie for the push](https://youtu.be/MaVRtYh1IRU).

**Comment by sayanarijit** [comment]
Include https://github.com/sayanarijit/xplr/issues/258#issuecomment-860037317

**Comment by sayanarijit** [comment]
Also document the fifo based previewer.

**Comment by sayanarijit** [comment]
Still WIP.

**Comment by sayanarijit** [comment]
Moved major parts of the [Wiki](https://github.com/sayanarijit/xplr/wiki) to https://arijitbasu.in/xplr/en/.

Still a lot to do.

**Comment by sayanarijit** [comment]
Hey @tobihans thanks for your interest in this project. Pls let me know which OS do you use and give me some time to write the instructions for you.

**Comment by tobihans** [comment]
Okay, I have a machine powered by Manjaro Linux.

**Comment by sayanarijit** [comment]
Top-level config has been fully documented in #357, thanks to @tobihans.

**Comment by sayanarijit** [comment]
Still some TODOs left. We should be able to close it soon.

**Comment by tobihans** [comment]
Hey, yes there is some remaining work. I was busy due to school, I'll try my best to finish it ASAP.

**Comment by sayanarijit** [comment]
@tobihans no worries, study & personal time comes first. I posted the update primarily to remind myself so that I don't get anxious when I revisit old issues.

**Comment by tobihans** [comment]
Okay, I understand, thanks.

**Comment by techdragon** [comment]
Just a suggestion, the "how do I use this" documentation is kind of lacking. You're documenting how to configure it and all the Lua internals... when coming to this as an existing user of `ranger` no stranger to text based file managers or `vim` style modal tools... I couldn't work out how to get it to do basic stuff like select a bunch of files then "copy and paste"/move them to another directory. So far the only basic operation I was able to intuitively master was multiple selection and then deletion. The help is... not great... since it just says I should be able to just use "m" but that doesn't work, so I look for documentation to make sure I'm using it correctly, and ... I've got nothing. No "how to use" documentation for basic operations at all.

**Comment by sayanarijit** [comment]
Hey, @techdragon thanks for the valuable feedback. However, I think the basic "how do I use this" guides would be more effective in video format instead of text, since it's a lot of content and writing/reading would be very time-consuming.

But, since it's a relatively new project, so far we got only [one video introducing xplr](https://youtu.be/MaVRtYh1IRU) which does cover copying and moving files (should we link it in the docs too?), and I hope there will be more videos soon.

(my voice and accent is horrible, so I can't really make great videos explaining stuff)

**Comment by sayanarijit** [comment]
All done :tada:
