### ISSUE TITLE
Improve the demo at xplr.dev

### ISSUE THREAD

**Issue by sayanarijit** [sayanarijit/xplr#389]
The GIF demo hosted on https://xplr.dev is a bit outdated and quite large, slowing the website down.

Let's create a demo video and display that instead.

We can keep the video [here](https://github.com/sayanarijit/xplr/tree/main/assets) which will get uploaded to the website.

Bonus: Showoff some video editing skills.

**Comment by igorepst** [comment]
You may use [SimpleScreenRecorder](https://www.maartenbaert.be/simplescreenrecorder/) to record video in MP4 format, making selection of the `xplr`'s terminal window or a rectangular region of a screen. IDK how to host the video on your site specifically, but apparently GitHub makes it possible to add video to Markdown files directly from it's builtin editor by pressing on 'Attach files by dragging...' at the bottom. See https://github.com/igorepst/context-switch.xplr/blob/main/README.md.
IMHO, it would be preferable not to add it to assets so it won't be downloaded during cloning (GH uploads it to user-images.githubusercontent.com) + using light background instead of dark.
If you wish I may record something tomorrow or on Friday

**Comment by sayanarijit** [comment]
@igorepst thanks for you input. I wanted to add the video in assets because it'd let me upload the video to cloudflare pages from where it'd be served. But I agree it'll bloat the size of the repo. I guess we can first record the demo and then decide whether keeping it in the repo would be a good idea, based on the size. If not, we need to use other hosting services as I don't think github readme is a good place to host video for another website.

> If you wish I may record something tomorrow or on Friday

Sure, go ahead. Not required, but see if you can highlight customisability using different themes and layouts. Might need some editing skills.

**Comment by igorepst** [comment]
I wrote a 'scenario'. Will record in the evening

**Comment by igorepst** [comment]
53 sec - 10 Mb - h264 1912x1036 30.000fps, incl. textual info
https://user-images.githubusercontent.com/1630792/141659603-7e486564-bb6f-4cd6-92ed-d9642b753112.mp4

Dark background part - 17 sec - 650 Kb - h264 1912x1036 30.056fps, without text

https://user-images.githubusercontent.com/1630792/141659674-da2228ae-6591-4c03-b641-4a029c10d0ed.mp4

Light background part - 35 sec - 1.3Mb - h264 1912x1036 30.028fps, without text

https://user-images.githubusercontent.com/1630792/141659703-9261a561-2d67-4f10-89d7-0f6d6e0b67a3.mp4

**Comment by sayanarijit** [comment]
Awesome...thanks 👍

**Comment by sayanarijit** [comment]
I'll try to find some opensource music that matches with the demo.

**Comment by sayanarijit** [comment]
Btw is there really a plugin implementing split?

**Comment by igorepst** [comment]
Depending on the terminal, yes, my `term.xplr`

**Comment by sayanarijit** [comment]
Ah ok that one...

**Comment by sayanarijit** [comment]
How about mixing with this music https://freemusicarchive.org/music/Monkey_Warhol/boots-pants-ep/boots-pants-sidekick-wave-instrumental-remix ?

**Comment by igorepst** [comment]
Nice music you found. If you want me to learn to add this track to the full video, please tell me from which second of the music to start. Otherwise, if you do it yourself, go for it.
BTW, beforehand, we may change text/cut out scenes/add something else to the video. After all, the decision and the approval should be yours

**Comment by sayanarijit** [comment]
Thanks, I have some (noob) experience with video editing, so I can do it once I get some time, but if you feel like learning, you can also do so. I don't really have any intention of nitpicking since this isn't vital to the core logic. The goal is to have fun, as long as the users aren't affected.

**Comment by sayanarijit** [comment]
As for `from which second of the music to start.`, I guess from the start should be fine.

**Comment by igorepst** [comment]
@sayanarijit The link to the video file with the audio is [here](https://drive.google.com/file/d/1_ZT2vCoKYjX7pn61DPbrl8lsWE5cYxy0/view?usp=sharing). The file is 11 Mb and is too big for GitHub. Please tell me when you download it so I may delete the file and this comment. Tnx

**Comment by sayanarijit** [comment]
> @sayanarijit The link to the video file with the audio is [here](https://drive.google.com/file/d/1_ZT2vCoKYjX7pn61DPbrl8lsWE5cYxy0/view?usp=sharing). The file is 11 Mb and is too big for GitHub. Please tell me when you download it so I may delete the file and this comment. Tnx

Cool. Done :+1:

**Comment by igorepst** [comment]
Hi. I was happy to contribute :)
It seems you have to attribute the music artist according to the license (https://creativecommons.org/licenses/by/4.0/), although I am not 100% sure, as `xplr` is in public domain. FYI

**Comment by sayanarijit** [comment]
Right, thanks, I have to attribute even if it's in public domain. At first, I added a link to the music, but now added full details just to be safe.
