### ISSUE TITLE
Improve config upgrade experience 

### ISSUE THREAD

**Issue by maximbaz** [sayanarijit/xplr#45]
Hello, I think upgrade experience is suboptimal and we can definitely make it easier / smoother in some ways. I just wanted to throw some ideas in, feedback welcome 🙂 

> v0.3.8 -> v0.3.12
> Just update the version in your config file.

This kind of upgrade sounds like it shouldn't require human intervention at all. Can we make `xplr` itself bump the version? Or make config version independent on `xplr` version, such that config version is `1`, `2`, `3`, ..., bumped only when needed, and `xplr` knows for example that `v0.3.8` requires config version of `12` ?

> xplr | yq ".config" -y | tee ~/.config/xplr/config.yml

I must say this is very cool idea, but maybe we can also provide a default config to make it a bit easier - you can do it in the repo (e.g. [kak-lsp](https://github.com/kak-lsp/kak-lsp) project keeps `kak-lsp.toml` in the repo and uses it [like so](https://github.com/kak-lsp/kak-lsp/blob/92ef7591a73ff2285ff2db82cc62fd8e084bb088/src/main.rs#L116-L130)) or if you don't think it's a good idea, we can also just generate the config file directly in the AUR pkg, and place it e.g. in `/usr/share/xplr/examples/config.yml` (cc @orhun).

> v0.3.7 -> v0.3.8
> ...
> Else, do the following:

Can we have this changelog not only in wiki, but also in the code / package somehow? Just imagining, I updated `xplr`, then disconnected from internet, and then I run `xplr` and uh-oh I must upgrade config but I dont know how without looking at the wiki!

Maybe a simple changelog file that we could also package?

And finally, maybe we can simplify config upgrade for Arch users even more if we leverage pacdiff? In that case honestly I might not even need to look in changelog, if only the lines changed that I didnt edit myself.

This would mean we would need to support reading config not only from `~/.config/xplr/config.yml` but also from `/etc/xplr/config.yml` (which is used only if there is no config in the user dir), and then in PKGBUILD we place the config here instead of in `examples` folder and mark it with `backup=` field (cc @orhun). It would require keeping config in `/etc` dir, so not sure if you like this, but I'm just brainstorming 🙂

**Comment by sayanarijit** [comment]
Hey thanks for inputs. I really wanted to get feedback from someone and brainstorm just like this.
As for the config file, I wouldn't want any app to update files in my config dir. Also, I don't think we should make it app version independent. Because that will complicate things. I'd prefer that users, just by looking at the version should me able to tell whether it's compatible or not. Also, there are 2 kinds of change, one is non-breaking feature addition, where for e.g. new messages are added without deprecating any other message. I want to find the least annoying way to inform users of such changes. For now, users will see a info level log for each change, which I agree isn't optimal. But the users can always ignore that and update the config without visiting the guide and that's ok. And then there are the breaking changes, where some messages are deprecated or replaced. So they'll have update their config file following the guide. And I'd also want to avoid making installation platform/packaging dependent. I like the in-repo config file idea and I think we can explore more in this line. The offline guide is also a great idea, but that has a drawback. I won't be able to change the docs once I ship a new version, so I'll have to be extremely careful and account for all possible scenarios when writing the upgrade guide. So maybe in future when the project is a bit stable, it'll be a good option.

**Comment by sayanarijit** [comment]
Updated the information in wiki: https://github.com/sayanarijit/xplr/wiki/Upgrade-Guide
Config file: https://github.com/sayanarijit/xplr/blob/main/src/config.yml

**Comment by maximbaz** [comment]
While we are brainstorming, here's another idea: what if users would only put in the config file what's different, not the entire config? And then xplr merges that small diff with the default config. And in that case maybe the versioning is not even needed, if I only have things in my config that I _wanted_ to change? Either they still work, or they no longer work (as in case of breaking change).

**Comment by sayanarijit** [comment]
I think this is how most other tools work. At first, I had doubts if this was possible at all with `xplr`, since `xplr` works more like a framework than a tool, exposing a bunch of messages and pipes, leaving it upto us how we use them. But now after some thinking I think it's possible to an extent. Though, I would still prefer `xplr` to fail and break than running outdated configs and behaving unexpectedly. Hence, I'm still reluctant to remove the version.

**Comment by sayanarijit** [comment]
Another way probably is to have a strong plugin system so that users don't have to use the messages themselves. Users can just install plugins, and it'll be up to the plugin authors to maintain compatibility. The plugin system should provide necessary validation against version incompatibilities.

**Comment by sayanarijit** [comment]
That said, I'll be stabilizing the messges and the api soon. So in the near future, there will be less breaking changes to look out for.

**Comment by sayanarijit** [comment]
I think incremental config update is the way to go. "Only add the part of config you want to change".

**Comment by maximbaz** [comment]
Now that we have incremental config, and we concluded that it's beneficial to keep the config versioned (at least for now), and we have `src/config.yml` with an example of full config with all the default values (@orhun could you pls make the package install this to `/usr/share/xplr/examples/config.yml`?), I think all my points got covered 🙂 Really nice job! Should we close this?

**Comment by sayanarijit** [comment]
Sure... Thanks all your valuable suggestions.

**Comment by orhun** [comment]
I couldn't step into the brainstorm but current state of the config file also seems fine to me.

@maximbaz done!
