### ISSUE TITLE
switch to default shell instead of bash

### ISSUE THREAD

**Issue by Creator54** [sayanarijit/xplr#499]
xplr 0.19.0
currently ":!" gives me bash want to use my default shell instead

**Comment by sayanarijit** [comment]
Hi, you can easily overwrite the default config. See https://xplr.dev/en/configuration

```lua
xplr.config.modes.builtin.action.key_bindings.on_key["!"].messages = {
  { Call = { command = "zsh", args = { "-i" } } },
  "ExplorePwdAsync",
  "PopMode",
}
```

**Comment by Creator54** [comment]
> Hi, you can easily overwrite the default config. See https://xplr.dev/en/configuration
> 
> ```lua
> xplr.config.modes.builtin.action.key_bindings.on_key["!"].messages = {
>   { Call = { command = "zsh", args = { "-i" } } },
>   "ExplorePwdAsync",
>   "PopMode",
> }
> ```

thanks, I am currently using this. However wouldn't it be better if xplr read the $SHELL and used it by default and have the option like here to change if anyone wanted.

**Comment by sayanarijit** [comment]
I guess that's the expected behavior. However, I believe a lot of zsh users (like me) are using oh-my-zsh and [there's an issue that require some workaround](https://github.com/ohmyzsh/ohmyzsh/issues/9859) to get xplr play nicely with it.

Though unrelated to xplr and zsh, I thought it'd be better if we solve this issue first before defaulting to $SHELL. Feel free share your thoughts.

**Comment by Creator54** [comment]
> I guess that's the expected behavior. However, I believe a lot of zsh users (like me) are using oh-my-zsh and [there's an issue that require some workaround](https://github.com/ohmyzsh/ohmyzsh/issues/9859) to get xplr play nicely with it.
> 
> Though unrelated to xplr and zsh, I thought it'd be better if we solve this issue first before defaulting to $SHELL. Feel free share your thoughts.

Yup tried zsh same for me too, hope it gets fixed soon.

**Comment by SaphiraKai** [comment]
In my opinion, completely ignoring the user's default shell setting just to prevent one edge case with one shell is too broad.

As a much less heavy-handed workaround, you could check for the existence of `$HOME/.oh-my-zsh/` and override to bash if it's found.

**Comment by SaphiraKai** [comment]
Here's a simple implementation of that I whacked together:
```diff
--- init.lua
+++ auto-shell-init.lua
@@ -1828,4 +1828,19 @@
 }
 
+-- Workaround https://github.com/ohmyzsh/ohmyzsh/issues/9859
+local function has_ohmyzsh()
+  local path = os.getenv("HOME").."/.oh-my-zsh"
+  local ok, err, code = os.rename(path, path)
+  if not ok then if code == 13 then return true end end
+  return ok, err
+end
+
+local function shell()
+  local shell = os.getenv("SHELL")
+  if shell == "/bin/zsh" and has_ohmyzsh() then
+    return "bash" else return shell
+  end
+end
+
 -- The builtin action mode.
 --
@@ -1839,5 +1854,5 @@
         messages = {
           "PopMode",
-          { Call0 = { command = "bash", args = { "-i" } } },
+          { Call0 = { command = shell(), args = { "-i" } } },
           "ExplorePwdAsync",
         },
```
When the issue is resolved, both functions can be deleted and the call to `shell()` can be replaced with `os.getenv("SHELL")`.

**Comment by sayanarijit** [comment]
> In my opinion, completely ignoring the user's default shell setting just to prevent one edge case with one shell is too broad.

Good point.

> As a much less heavy-handed workaround, you could check for the existence of $HOME/.oh-my-zsh/ and override to bash if it's found.

I wouldn't, because workarounds like this often lead to hacky and unmaintainable code. For e.g. imagine fish, nushell, etc. and countless other shells require workarounds like this too. Since bash is a dependency for xplr, and it is heavily tested, defaulting to bash seemed like a safer option.

However, I think we should try defaulting to $SHELL and see what happens. Maybe users facing this issue will come up with a good solution that we've been missing.
