### ISSUE TITLE
should handle filenames containing newlines

### ISSUE THREAD

**Issue by jmcantrell** [sayanarijit/xplr#515]
It's regrettable, but on some filesystems, filenames are allowed to contain newlines. This causes a number of problems with the way xplr handles them.

Some that I've noticed:
1. In the directory listing, the filename is cut off at the newline
2. When the cursor is highlighting a filename containing a newline, the end marker for the highlight is missing (the ']', by default)
3. When --write0 is not used, the filename containing a newline is sent to stdout unchanged, appearing as two separate lines
4. When --write0 is used, the newline in the filename gets turned into a null, causing selection sent to stdout to appear to have two files

How I think these situations should be handled:
1. The filename should display newlines escaped e.g. `foo$'\n'bar` (like how `ls` displays it). I'm not sure if this is possible, but the escaped newline should be highlighted somehow to indicate that it's a special char.
2. This might resolve itself, once the filename display function handles newlines correctly
3. This is expected and probably the correct way to handle it
4. This should behave like 3, where the newline is output unchanged

I'm going to update this issue as I'm investigating, and hopefully offer a PR as soon as I get more familiar with the codebase. Any input or guidance is appreciated.

**Comment by dtomvan** [comment]
Yup, your first point is caused by the way we are currently using tui's API. Currently, we reserve 1 line (`Spans` instance) per file. The file name get's inserted by xplr's default column renderer [as seen in the default init.lua](https://github.com/sayanarijit/xplr/blob/57483bef41d93b8380a9aaabc2cfaa37a87ebc0f/src/init.lua#L2503). This can already be changed by the user by intercepting the filename with `string.gsub`. We should probably change this as well in the default config.

**Comment by dtomvan** [comment]
Your fourth point is currently caused by xplr creating the `-0` output by taking whatever output xplr will produce on exit, and replacing any occurence of `\n` with `\0`. This is probably not what should be done anyways, because the `PrintAppStateAndQuit` message will output a yml document, which isn't what `--print0` is/should be used for.

**Comment by sayanarijit** [comment]
> We should probably change this as well in the default config.

Correct. Escaping the newlines in the ui (lua) should fix this.

**Comment by sayanarijit** [comment]
But this raises other issues... We're using newlines as the separator in the output pipes... Basic shell operations on thise files probably won't work. In that case, we'll probably need to update the backend (rust) to convers the newlines to null (\0) and the config to convert them back to newline before executing commands.

**Comment by sayanarijit** [comment]
The proper way would be to use \0 as the separator, but while this makes it easy for machine to read the list, humans will find it hard to work with \0. Separating filenames with \n and convert \n in filenames into \0 will add some annoyance dealing with such files, but for the majority, it's much more convenient. I hope alteast using \0 in filenames is illegal.

**Comment by jmcantrell** [comment]
> We're using newlines as the separator in the output pipes

Are you referring to [this](https://github.com/sayanarijit/xplr/blob/main/src/init.lua#L1477-L1479) kind of thing?

When you say "basic shell operations", do you mean the various usages of `BashExec` in `init.lua`?

**Comment by sayanarijit** [comment]
@jmcantrell correct.

**Comment by sayanarijit** [comment]
But yes, will look into your proposed solution too. This sounds more "proper", but will have to check feasibility.

**Comment by sayanarijit** [comment]
And you're write about --read/write0 too. Need to fix this.

**Comment by sayanarijit** [comment]
Also, thanks a lot for looking into this, and sorry about the messy codebase. I plan to do a refactor before the next release.
