### ISSUE TITLE
Config file XDG conformance 

### ISSUE THREAD

**Issue by SolitudeSF** [sayanarijit/xplr#627]
Config directory should default to `$XDG_CONFIG_HOME/xplr` with fallback to `$HOME/.config/xplr`.

**Comment by sayanarijit** [comment]
This would be a huge breaking change.
As far as my preference goes, ~/. config is the way to go for all CLI/TUI based tools, both on linux and bsd, including mac.
Could you pls confirm the OS you're using so that I can dig deeper into the issue?

**Comment by SolitudeSF** [comment]
linux.

**Comment by sayanarijit** [comment]
@noahmayr said:

---

From what I understand this will break on MacOS. The dirs crate will give you MacOS specific paths like ~/Library/Application Support/xplr. Even though I'm explicitly setting $XDG_CONFIG_HOME, the maintainers of the dirs and directories crates are actively refusing to honor an environment variable intentionally set by MacOS users due to what sounds like "Apple knows best and it's your own fault for choosing a such a locked down system". Meanwhile 99% of CLI programs use ~/.config/* on MacOS or at least respect the $XDG_CONFIG_HOME environment variable.

@sayanarijit can we please hold back on releasing this until previous default behavior has been restored? This will be especially painful for those wanting to sync their dotfiles.

---

**Comment by sayanarijit** [comment]
@noahmayr thanks for raising the concern.

I currently don't have access to a mac, so can't dig into it right now. But yes, I'm not releasing a new version without testing it on a mac.

**Comment by sayanarijit** [comment]
There's this library we can try: https://whitequark.github.io/rust-xdg/xdg/struct.BaseDirectories.html

**Comment by sayanarijit** [comment]
Closing this as fixed.
