### ISSUE TITLE
Scrolling help and selection panes

### ISSUE THREAD

**Issue by duganchen** [sayanarijit/xplr#648]
I'm sorry to have to ask this, but how do I scroll the help and selection panes if there are too many entries to fit in them and all be visible onscreen? I couldn't find this information in the docs or in the default init.lua.

**Comment by sayanarijit** [comment]
Terminal height is limited, so no matter how much you scale, it'll eventually run out of space. That's why there's :sl to list the selection in a pager, and ? to display the global help menu. You can maybe hack it to display only the current mode help menu instead of global.

Also, setting the mode.layout = "HelpMenu" for intermediate modes will display full screen help menu, like it does in action mode.
