### ISSUE TITLE
How about adding a command line to enhance the usability?

### ISSUE THREAD

**Issue by uuhan** [sayanarijit/xplr#683]
<img width="1678" alt="how" src="https://github.com/sayanarijit/xplr/assets/3286111/8ab84305-a3ec-48c9-8894-e63942017c54">

Like vim does.

**Comment by sayanarijit** [comment]
Im not sure how useful it will be since we don’t have that rich of a lua api. Most of the file management work are better done with cli commands ([see map.xplr](https://blog.xplr.dev/post/28432/Execute-batch-operations-using-xplr)).

For more complex/custom operations, there’s [command-lmode.xplr](https://blog.xplr.dev/post/28557/Forget-key-bindings-and-get-yourself-a-command-mode).

**Comment by uuhan** [comment]
> Im not sure how useful it will be since we don’t have that rich of a lua api. Most of the file management work are better done with cli commands ([see map.xplr](https://blog.xplr.dev/post/28432/Execute-batch-operations-using-xplr)).
> 
> For more complex/custom operations, there’s [command-mode.xplr](https://blog.xplr.dev/post/28557/Forget-key-bindings-and-get-yourself-a-command-mode).

@sayanarijit 

I just create an empty init.lua file:

```bash
mkdir -p ~/.config/xplr && touch ~/.config/xplr/init.lua
```

but xplr failed to startup with error:

```log
22:20:14|ERROR) 'version' must be defined globally in ~/.config/xplr/init.lua
```

Do I miss some configuration? My system is macos.

**Comment by uuhan** [comment]
> Im not sure how useful it will be since we don’t have that rich of a lua api. Most of the file management work are better done with cli commands ([see map.xplr](https://blog.xplr.dev/post/28432/Execute-batch-operations-using-xplr)).
> 
> For more complex/custom operations, there’s [command-mode.xplr](https://blog.xplr.dev/post/28557/Forget-key-bindings-and-get-yourself-a-command-mode).

This seems what I need. Awesome!
