### ISSUE TITLE
Suggestion: size support (column, sorting)

### ISSUE THREAD

**Issue by maximbaz** [sayanarijit/xplr#84]
What are your thoughts on adding support for file sizes? To have a column with file size, to be able to sort by them?

`ncdu` integration as you've shown in wiki is nice, and maybe it's enough, I was just thinking about it, and (a) for me personally, a size column would probably be more interesting than mime or index, and (b) some operations like system cleaning although possible to do in `ncdu`, might be more pleasant to do in `xplr`.

bonus points: directory sizes, something that even `exa` doesn't support 🙂

**Comment by sayanarijit** [comment]
I don't want to implement a full `disk analyze` mode now because there are dedicated tools that are much better at this [and I'd like `xplr` to integrate with them at a deeper level](https://github.com/Byron/dua-cli/issues/87).
Although, file size seems doable since it's just lying around in the metadata.

**Comment by sayanarijit** [comment]
Maybe in the future it'll be possible to run a disk analyzer as a service that will set extra properties to the nodes like `meta.disk_usage` via pipes, and it'll be possible to sort/filter using meta fields.
